version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:11.5
    ports:
    - "5432:5432"
    volumes:
    - postgresdata:/data/postgres
    - postgresdbdata:/var/lib/postgresql/data
    env_file:
    - docker.env
    networks:
    - postgres

volumes:
  postgresdata:
    driver: local
  postgresdbdata:
    driver: local

networks:
  postgres:
    driver: bridge